// Quran constants with JSON-based verse loading
import { loadSurahVerses, loadSurahVersesByNumber } from './quran-data/loadSurahVerses';

export interface Verse {
  number: number;
  arabic: string;
  translation: string;
  transliteration: string;
  juz: number;
  page: number;
  ruku: number;
  sajda: boolean;
}

export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  englishName: string;
  verses: number;
  juz: number;
  type: "Meccan" | "Medinan";
  revelationOrder: number;
  description: string;
  bismillah: string;
  versesData: Verse[];
  versesFile?: string; // Key for loading verses from JSON
}

// Complete list of all 114 surahs
export const QURAN_SURAHS: Surah[] = [
  {
    number: 1,
    name: "Al-Fatihah",
    arabicName: "الفاتحة",
    englishName: "The Opening",
    verses: 7,
    juz: 1,
    type: "Meccan",
    revelationOrder: 5,
    description: "The Opening chapter.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "fatiha",
  },
  {
    number: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    englishName: "The Cow",
    verses: 286,
    juz: 1,
    type: "Medinan",
    revelationOrder: 87,
    description: "The Cow.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "baqarah",
  },
  {
    number: 3,
    name: "Al-Imran",
    arabicName: "آل عمران",
    englishName: "The Family of Imran",
    verses: 200,
    juz: 3,
    type: "Medinan",
    revelationOrder: 89,
    description: "The Family of Imran.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "imran",
  },
  {
    number: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    englishName: "The Women",
    verses: 176,
    juz: 4,
    type: "Medinan",
    revelationOrder: 92,
    description: "The Women.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "nisa",
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    englishName: "The Table Spread",
    verses: 120,
    juz: 6,
    type: "Medinan",
    revelationOrder: 112,
    description: "The Table Spread.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "maidah",
  },
  {
    number: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    englishName: "The Cattle",
    verses: 165,
    juz: 7,
    type: "Meccan",
    revelationOrder: 55,
    description: "The Cattle.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "anam",
  },
  {
    number: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    englishName: "The Heights",
    verses: 206,
    juz: 8,
    type: "Meccan",
    revelationOrder: 39,
    description: "The Heights.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "araf",
  },
  {
    number: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    englishName: "The Spoils of War",
    verses: 75,
    juz: 9,
    type: "Medinan",
    revelationOrder: 88,
    description: "The Spoils of War.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "anfal",
  },
  {
    number: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    englishName: "The Repentance",
    verses: 129,
    juz: 10,
    type: "Medinan",
    revelationOrder: 113,
    description: "The Repentance.",
    bismillah: "",
    versesData: [],
    versesFile: "tawbah",
  },
  {
    number: 10,
    name: "Yunus",
    arabicName: "يونس",
    englishName: "Jonah",
    verses: 109,
    juz: 11,
    type: "Meccan",
    revelationOrder: 51,
    description: "Jonah.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "yunus",
  },
  {
    number: 11,
    name: "Hud",
    arabicName: "هود",
    englishName: "Hud",
    verses: 123,
    juz: 11,
    type: "Meccan",
    revelationOrder: 52,
    description: "Named after Prophet Hud.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hud",
  },
  {
    number: 12,
    name: "Yusuf",
    arabicName: "يوسف",
    englishName: "Joseph",
    verses: 111,
    juz: 12,
    type: "Meccan",
    revelationOrder: 53,
    description: "The story of Prophet Joseph.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "yusuf",
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    arabicName: "الرعد",
    englishName: "The Thunder",
    verses: 43,
    juz: 13,
    type: "Medinan",
    revelationOrder: 96,
    description: "Named after thunder.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "rad",
  },
  {
    number: 14,
    name: "Ibrahim",
    arabicName: "إبراهيم",
    englishName: "Abraham",
    verses: 52,
    juz: 13,
    type: "Meccan",
    revelationOrder: 72,
    description: "Named after Prophet Abraham.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ibrahim",
  },
  {
    number: 15,
    name: "Al-Hijr",
    arabicName: "الحجر",
    englishName: "The Rock",
    verses: 99,
    juz: 14,
    type: "Meccan",
    revelationOrder: 54,
    description: "Named after the rocky region of Hijr.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hijr",
  },
  {
    number: 16,
    name: "An-Nahl",
    arabicName: "النحل",
    englishName: "The Bee",
    verses: 128,
    juz: 14,
    type: "Meccan",
    revelationOrder: 70,
    description: "Named after the bee.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "nahl",
  },
  {
    number: 17,
    name: "Al-Isra",
    arabicName: "الإسراء",
    englishName: "The Night Journey",
    verses: 111,
    juz: 15,
    type: "Meccan",
    revelationOrder: 50,
    description: "The Night Journey of Prophet Muhammad.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "isra",
  },
  {
    number: 18,
    name: "Al-Kahf",
    arabicName: "الكهف",
    englishName: "The Cave",
    verses: 110,
    juz: 15,
    type: "Meccan",
    revelationOrder: 69,
    description: "The story of the companions of the cave.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "kahf",
  },
  {
    number: 19,
    name: "Maryam",
    arabicName: "مريم",
    englishName: "Mary",
    verses: 98,
    juz: 16,
    type: "Meccan",
    revelationOrder: 44,
    description: "Named after Mary, mother of Jesus.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "maryam",
  },
  {
    number: 20,
    name: "Ta-Ha",
    arabicName: "طه",
    englishName: "Ta-Ha",
    verses: 135,
    juz: 16,
    type: "Meccan",
    revelationOrder: 45,
    description: "Named after the mysterious letters Ta-Ha.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "taha",
  },
  {
    number: 21,
    name: "Al-Anbiya",
    arabicName: "الأنبياء",
    englishName: "The Prophets",
    verses: 112,
    juz: 17,
    type: "Meccan",
    revelationOrder: 73,
    description: "Stories of various prophets.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "anbya",
  },
  {
    number: 22,
    name: "Al-Hajj",
    arabicName: "الحج",
    englishName: "The Pilgrimage",
    verses: 78,
    juz: 17,
    type: "Medinan",
    revelationOrder: 103,
    description: "The pilgrimage to Mecca.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hajj",
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    englishName: "The Believers",
    verses: 118,
    juz: 18,
    type: "Meccan",
    revelationOrder: 74,
    description: "Characteristics of true believers.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "muminoon",
  },
  {
    number: 24,
    name: "An-Nur",
    arabicName: "النور",
    englishName: "The Light",
    verses: 64,
    juz: 18,
    type: "Medinan",
    revelationOrder: 102,
    description: "The light of divine guidance.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "nur",
  },
  {
    number: 25,
    name: "Al-Furqan",
    arabicName: "الفرقان",
    englishName: "The Criterion",
    verses: 77,
    juz: 18,
    type: "Meccan",
    revelationOrder: 42,
    description: "The criterion between right and wrong.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "furqan",
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: "الشعراء",
    englishName: "The Poets",
    verses: 227,
    juz: 19,
    type: "Meccan",
    revelationOrder: 47,
    description: "Named after the poets.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "shuara",
  },
  {
    number: 27,
    name: "An-Naml",
    arabicName: "النمل",
    englishName: "The Ant",
    verses: 93,
    juz: 19,
    type: "Meccan",
    revelationOrder: 48,
    description: "Named after the ant in Solomon's story.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "naml",
  },
  {
    number: 28,
    name: "Al-Qasas",
    arabicName: "القصص",
    englishName: "The Stories",
    verses: 88,
    juz: 20,
    type: "Meccan",
    revelationOrder: 49,
    description: "The stories of previous nations.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qasas",
  },
  {
    number: 29,
    name: "Al-Ankabut",
    arabicName: "العنكبوت",
    englishName: "The Spider",
    verses: 69,
    juz: 20,
    type: "Meccan",
    revelationOrder: 85,
    description: "Named after the spider's web metaphor.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ankabut",
  },
  {
    number: 30,
    name: "Ar-Rum",
    arabicName: "الروم",
    englishName: "The Romans",
    verses: 60,
    juz: 21,
    type: "Meccan",
    revelationOrder: 84,
    description: "Named after the Roman Empire.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "rum",
  },
  {
    number: 31,
    name: "Luqman",
    arabicName: "لقمان",
    englishName: "Luqman",
    verses: 34,
    juz: 21,
    type: "Meccan",
    revelationOrder: 57,
    description: "Named after the wise man Luqman.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "luqman",
  },
  {
    number: 32,
    name: "As-Sajdah",
    arabicName: "السجدة",
    englishName: "The Prostration",
    verses: 30,
    juz: 21,
    type: "Meccan",
    revelationOrder: 75,
    description: "Named after prostration in worship.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "sajdah",
  },
  {
    number: 33,
    name: "Al-Ahzab",
    arabicName: "الأحزاب",
    englishName: "The Confederates",
    verses: 73,
    juz: 21,
    type: "Medinan",
    revelationOrder: 90,
    description: "The confederate tribes that attacked Medina.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ahzab",
  },
  {
    number: 34,
    name: "Saba",
    arabicName: "سبأ",
    englishName: "Sheba",
    verses: 54,
    juz: 22,
    type: "Meccan",
    revelationOrder: 58,
    description: "Named after the kingdom of Sheba.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "saba",
  },
  {
    number: 35,
    name: "Fatir",
    arabicName: "فاطر",
    englishName: "The Creator",
    verses: 45,
    juz: 22,
    type: "Meccan",
    revelationOrder: 43,
    description: "Allah as the creator of all things.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "fatir",
  },
  {
    number: 36,
    name: "Ya-Sin",
    arabicName: "يس",
    englishName: "Ya-Sin",
    verses: 83,
    juz: 23,
    type: "Meccan",
    revelationOrder: 41,
    description: "Named after the mysterious letters Ya-Sin.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "yasin",
  },
  {
    number: 37,
    name: "As-Saffat",
    arabicName: "الصافات",
    englishName: "Those Who Set The Ranks",
    verses: 182,
    juz: 23,
    type: "Meccan",
    revelationOrder: 56,
    description: "The angels who arrange themselves in ranks.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "saffat",
  },
  {
    number: 38,
    name: "Sad",
    arabicName: "ص",
    englishName: "Sad",
    verses: 88,
    juz: 23,
    type: "Meccan",
    revelationOrder: 38,
    description: "Named after the Arabic letter Sad.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "sad",
  },
  {
    number: 39,
    name: "Az-Zumar",
    arabicName: "الزمر",
    englishName: "The Troops",
    verses: 75,
    juz: 23,
    type: "Meccan",
    revelationOrder: 59,
    description: "The troops of believers and disbelievers.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "zumar",
  },
  {
    number: 40,
    name: "Ghafir",
    arabicName: "غافر",
    englishName: "The Forgiver",
    verses: 85,
    juz: 24,
    type: "Meccan",
    revelationOrder: 60,
    description: "Allah as the forgiver of sins.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ghafir",
  },
  {
    number: 41,
    name: "Fussilat",
    arabicName: "فصلت",
    englishName: "Explained In Detail",
    verses: 54,
    juz: 24,
    type: "Meccan",
    revelationOrder: 61,
    description: "The Quran explained in detail.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "fussilat",
  },
  {
    number: 42,
    name: "Ash-Shura",
    arabicName: "الشورى",
    englishName: "The Consultation",
    verses: 53,
    juz: 25,
    type: "Meccan",
    revelationOrder: 62,
    description: "Consultation in community affairs.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "shura",
  },
  {
    number: 43,
    name: "Az-Zukhruf",
    arabicName: "الزخرف",
    englishName: "The Ornaments Of Gold",
    verses: 89,
    juz: 25,
    type: "Meccan",
    revelationOrder: 63,
    description: "The ornaments and decorations of worldly life.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "zukhruf",
  },
  {
    number: 44,
    name: "Ad-Dukhan",
    arabicName: "الدخان",
    englishName: "The Smoke",
    verses: 59,
    juz: 25,
    type: "Meccan",
    revelationOrder: 64,
    description: "The smoke that will appear before the Day of Judgment.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "dukhan",
  },
  {
    number: 45,
    name: "Al-Jathiyah",
    arabicName: "الجاثية",
    englishName: "The Crouching",
    verses: 37,
    juz: 25,
    type: "Meccan",
    revelationOrder: 65,
    description: "People crouching on their knees on Judgment Day.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "jathiyah",
  },
  {
    number: 46,
    name: "Al-Ahqaf",
    arabicName: "الأحقاف",
    englishName: "The Winding Sand-tracts",
    verses: 35,
    juz: 26,
    type: "Meccan",
    revelationOrder: 66,
    description: "The curved sand hills where the people of Ad lived.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ahqaf",
  },
  {
    number: 47,
    name: "Muhammad",
    arabicName: "محمد",
    englishName: "Muhammad",
    verses: 38,
    juz: 26,
    type: "Medinan",
    revelationOrder: 95,
    description: "Named after Prophet Muhammad.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "muhammad",
  },
  {
    number: 48,
    name: "Al-Fath",
    arabicName: "الفتح",
    englishName: "The Victory",
    verses: 29,
    juz: 26,
    type: "Medinan",
    revelationOrder: 111,
    description: "The victory and conquest of Mecca.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "fath",
  },
  {
    number: 49,
    name: "Al-Hujurat",
    arabicName: "الحجرات",
    englishName: "The Private Apartments",
    verses: 18,
    juz: 26,
    type: "Medinan",
    revelationOrder: 106,
    description: "The private apartments of Prophet Muhammad.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hujurat",
  },
  {
    number: 50,
    name: "Qaf",
    arabicName: "ق",
    englishName: "Qaf",
    verses: 45,
    juz: 26,
    type: "Meccan",
    revelationOrder: 34,
    description: "Named after the Arabic letter Qaf.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qaf",
  },
  {
    number: 51,
    name: "Adh-Dhariyat",
    arabicName: "الذاريات",
    englishName: "The Winnowing Winds",
    verses: 60,
    juz: 26,
    type: "Meccan",
    revelationOrder: 67,
    description: "The winds that scatter dust.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "dhariyat",
  },
  {
    number: 52,
    name: "At-Tur",
    arabicName: "الطور",
    englishName: "The Mount",
    verses: 49,
    juz: 27,
    type: "Meccan",
    revelationOrder: 76,
    description: "Mount Sinai where Moses received the Torah.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "tur",
  },
  {
    number: 53,
    name: "An-Najm",
    arabicName: "النجم",
    englishName: "The Star",
    verses: 62,
    juz: 27,
    type: "Meccan",
    revelationOrder: 23,
    description: "The star by which one navigates.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "najm",
  },
  {
    number: 54,
    name: "Al-Qamar",
    arabicName: "القمر",
    englishName: "The Moon",
    verses: 55,
    juz: 27,
    type: "Meccan",
    revelationOrder: 37,
    description: "The splitting of the moon.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qamar",
  },
  {
    number: 55,
    name: "Ar-Rahman",
    arabicName: "الرحمن",
    englishName: "The Beneficent",
    verses: 78,
    juz: 27,
    type: "Meccan",
    revelationOrder: 97,
    description: "Allah, the Most Merciful.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "rahman",
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    arabicName: "الواقعة",
    englishName: "The Inevitable",
    verses: 96,
    juz: 27,
    type: "Meccan",
    revelationOrder: 46,
    description: "The inevitable Day of Judgment.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "waqiah",
  },
  {
    number: 57,
    name: "Al-Hadid",
    arabicName: "الحديد",
    englishName: "The Iron",
    verses: 29,
    juz: 27,
    type: "Medinan",
    revelationOrder: 94,
    description: "Iron and its strength.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hadid",
  },
  {
    number: 58,
    name: "Al-Mujadila",
    arabicName: "المجادلة",
    englishName: "The Pleading Woman",
    verses: 22,
    juz: 28,
    type: "Medinan",
    revelationOrder: 105,
    description: "The woman who pleaded her case to the Prophet.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "mujadila",
  },
  {
    number: 59,
    name: "Al-Hashr",
    arabicName: "الحشر",
    englishName: "The Exile",
    verses: 24,
    juz: 28,
    type: "Medinan",
    revelationOrder: 101,
    description: "The exile of the Jewish tribe Banu Nadir.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "hashr",
  },
  {
    number: 60,
    name: "Al-Mumtahanah",
    arabicName: "الممتحنة",
    englishName: "She That Is To Be Examined",
    verses: 13,
    juz: 28,
    type: "Medinan",
    revelationOrder: 91,
    description: "The woman who is to be tested.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "mumtahanah",
  },
  {
    number: 61,
    name: "As-Saff",
    arabicName: "الصف",
    englishName: "The Ranks",
    verses: 14,
    juz: 28,
    type: "Medinan",
    revelationOrder: 109,
    description: "Standing in ranks for battle.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "saf",
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    arabicName: "الجمعة",
    englishName: "The Congregation",
    verses: 11,
    juz: 28,
    type: "Medinan",
    revelationOrder: 110,
    description: "The Friday congregation prayer.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "jumuah",
  },
  {
    number: 63,
    name: "Al-Munafiqun",
    arabicName: "المنافقون",
    englishName: "The Hypocrites",
    verses: 11,
    juz: 28,
    type: "Medinan",
    revelationOrder: 104,
    description: "The hypocrites in the Muslim community.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "munafiqun",
  },
  {
    number: 64,
    name: "At-Taghabun",
    arabicName: "التغابن",
    englishName: "The Mutual Disillusion",
    verses: 18,
    juz: 28,
    type: "Medinan",
    revelationOrder: 108,
    description: "The mutual loss and gain on Judgment Day.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "taghabun",
  },
  {
    number: 65,
    name: "At-Talaq",
    arabicName: "الطلاق",
    englishName: "The Divorce",
    verses: 12,
    juz: 28,
    type: "Medinan",
    revelationOrder: 99,
    description: "Laws regarding divorce.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "talaq",
  },
  {
    number: 66,
    name: "At-Tahrim",
    arabicName: "التحريم",
    englishName: "The Prohibition",
    verses: 12,
    juz: 28,
    type: "Medinan",
    revelationOrder: 107,
    description: "The prohibition of what Allah has made lawful.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "tahrim",
  },
  {
    number: 67,
    name: "Al-Mulk",
    arabicName: "الملك",
    englishName: "The Sovereignty",
    verses: 30,
    juz: 29,
    type: "Meccan",
    revelationOrder: 77,
    description: "The sovereignty and dominion of Allah.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "mulk",
  },
  {
    number: 68,
    name: "Al-Qalam",
    arabicName: "القلم",
    englishName: "The Pen",
    verses: 52,
    juz: 29,
    type: "Meccan",
    revelationOrder: 2,
    description: "The pen and what it writes.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qalam",
  },
  {
    number: 69,
    name: "Al-Haqqah",
    arabicName: "الحاقة",
    englishName: "The Reality",
    verses: 52,
    juz: 29,
    type: "Meccan",
    revelationOrder: 78,
    description: "The ultimate reality of the Hereafter.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "haqqah",
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    arabicName: "المعارج",
    englishName: "The Ascending Stairways",
    verses: 44,
    juz: 29,
    type: "Meccan",
    revelationOrder: 79,
    description: "The ascending stairways to heaven.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "maarij",
  },
  {
    number: 71,
    name: "Nuh",
    arabicName: "نوح",
    englishName: "Noah",
    verses: 28,
    juz: 29,
    type: "Meccan",
    revelationOrder: 71,
    description: "The story of Prophet Noah.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "nuh",
  },
  {
    number: 72,
    name: "Al-Jinn",
    arabicName: "الجن",
    englishName: "The Jinn",
    verses: 28,
    juz: 29,
    type: "Meccan",
    revelationOrder: 40,
    description: "The invisible beings (jinn).",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "jinn",
  },
  {
    number: 73,
    name: "Al-Muzzammil",
    arabicName: "المزمل",
    englishName: "The Enshrouded One",
    verses: 20,
    juz: 29,
    type: "Meccan",
    revelationOrder: 3,
    description: "The one wrapped in garments.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "muzzammil",
  },
  {
    number: 74,
    name: "Al-Muddaththir",
    arabicName: "المدثر",
    englishName: "The Cloaked One",
    verses: 56,
    juz: 29,
    type: "Meccan",
    revelationOrder: 4,
    description: "The one covered in a cloak.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "muddathir",
  },
  {
    number: 75,
    name: "Al-Qiyamah",
    arabicName: "القيامة",
    englishName: "The Resurrection",
    verses: 40,
    juz: 29,
    type: "Meccan",
    revelationOrder: 31,
    description: "The Day of Resurrection.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qiyamah",
  },
  {
    number: 76,
    name: "Al-Insan",
    arabicName: "الإنسان",
    englishName: "The Human",
    verses: 31,
    juz: 29,
    type: "Medinan",
    revelationOrder: 98,
    description: "The human being.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "insan",
  },
  {
    number: 77,
    name: "Al-Mursalat",
    arabicName: "المرسلات",
    englishName: "The Emissaries",
    verses: 50,
    juz: 29,
    type: "Meccan",
    revelationOrder: 33,
    description: "The winds sent forth.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "mursalat",
  },
  {
    number: 78,
    name: "An-Naba",
    arabicName: "النبأ",
    englishName: "The Tidings",
    verses: 40,
    juz: 30,
    type: "Meccan",
    revelationOrder: 80,
    description: "The great news of the Hereafter.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "naba",
  },
  {
    number: 79,
    name: "An-Nazi'at",
    arabicName: "النازعات",
    englishName: "Those Who Drag Forth",
    verses: 46,
    juz: 30,
    type: "Meccan",
    revelationOrder: 81,
    description: "The angels who drag forth souls.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "naziyat",
  },
  {
    number: 80,
    name: "Abasa",
    arabicName: "عبس",
    englishName: "He Frowned",
    verses: 42,
    juz: 30,
    type: "Meccan",
    revelationOrder: 24,
    description: "He frowned and turned away.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "abasa",
  },
  {
    number: 81,
    name: "At-Takwir",
    arabicName: "التكوير",
    englishName: "The Overthrowing",
    verses: 29,
    juz: 30,
    type: "Meccan",
    revelationOrder: 7,
    description: "The folding up of the sun.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "takwir",
  },
  {
    number: 82,
    name: "Al-Infitar",
    arabicName: "الإنفطار",
    englishName: "The Cleaving",
    verses: 19,
    juz: 30,
    type: "Meccan",
    revelationOrder: 82,
    description: "The cleaving asunder of the sky.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "infitar",
  },
  {
    number: 83,
    name: "Al-Mutaffifin",
    arabicName: "المطففين",
    englishName: "The Defrauding",
    verses: 36,
    juz: 30,
    type: "Meccan",
    revelationOrder: 86,
    description: "Those who give less than due.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "mutaffifin",
  },
  {
    number: 84,
    name: "Al-Inshiqaq",
    arabicName: "الإنشقاق",
    englishName: "The Splitting Open",
    verses: 25,
    juz: 30,
    type: "Meccan",
    revelationOrder: 83,
    description: "The splitting open of the heaven.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "inshiqaq",
  },
  {
    number: 85,
    name: "Al-Buruj",
    arabicName: "البروج",
    englishName: "The Mansions Of The Stars",
    verses: 22,
    juz: 30,
    type: "Meccan",
    revelationOrder: 27,
    description: "The constellations in the sky.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "buruj",
  },
  {
    number: 86,
    name: "At-Tariq",
    arabicName: "الطارق",
    englishName: "The Morning Star",
    verses: 17,
    juz: 30,
    type: "Meccan",
    revelationOrder: 36,
    description: "The night-visitant (the bright star).",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "tariq",
  },
  {
    number: 87,
    name: "Al-A'la",
    arabicName: "الأعلى",
    englishName: "The Most High",
    verses: 19,
    juz: 30,
    type: "Meccan",
    revelationOrder: 8,
    description: "The Most High (Allah).",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ala",
  },
  {
    number: 88,
    name: "Al-Ghashiyah",
    arabicName: "الغاشية",
    englishName: "The Overwhelming",
    verses: 26,
    juz: 30,
    type: "Meccan",
    revelationOrder: 68,
    description: "The overwhelming event (Judgment Day).",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "ghashiyah",
  },
  {
    number: 89,
    name: "Al-Fajr",
    arabicName: "الفجر",
    englishName: "The Dawn",
    verses: 30,
    juz: 30,
    type: "Meccan",
    revelationOrder: 10,
    description: "The break of day.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "fajr",
  },
  {
    number: 90,
    name: "Al-Balad",
    arabicName: "البلد",
    englishName: "The City",
    verses: 20,
    juz: 30,
    type: "Meccan",
    revelationOrder: 35,
    description: "The city (Mecca).",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "balad",
  },
  {
    number: 91,
    name: "Ash-Shams",
    arabicName: "الشمس",
    englishName: "The Sun",
    verses: 15,
    juz: 30,
    type: "Meccan",
    revelationOrder: 26,
    description: "The sun and its brightness.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "shams",
  },
  {
    number: 92,
    name: "Al-Layl",
    arabicName: "الليل",
    englishName: "The Night",
    verses: 21,
    juz: 30,
    type: "Meccan",
    revelationOrder: 9,
    description: "The night when it covers.",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "layl",
  },
  {
    number: 93,
    name: "Ad-Duha",
    arabicName: "الضحى",
    englishName: "The Morning Hours",
    verses: 11,
    juz: 30,
    type: "Meccan",
    revelationOrder: 11,
    description: "The bright morning hours.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "adduha",
  },
  {
    number: 94,
    name: "Ash-Sharh",
    arabicName: "الشرح",
    englishName: "The Relief",
    verses: 8,
    juz: 30,
    type: "Meccan",
    revelationOrder: 12,
    description: "The expansion of the breast.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "sharh",
  },
  {
    number: 95,
    name: "At-Tin",
    arabicName: "التين",
    englishName: "The Fig",
    verses: 8,
    juz: 30,
    type: "Meccan",
    revelationOrder: 28,
    description: "The fig and the olive.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "tin",
  },
  {
    number: 96,
    name: "Al-Alaq",
    arabicName: "العلق",
    englishName: "The Clinging Clot",
    verses: 19,
    juz: 30,
    type: "Meccan",
    revelationOrder: 1,
    description: "The clinging clot (embryo).",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "alaq",
  },
  {
    number: 97,
    name: "Al-Qadr",
    arabicName: "القدر",
    englishName: "The Power",
    verses: 5,
    juz: 30,
    type: "Meccan",
    revelationOrder: 25,
    description: "The Night of Power.",
    bismillah: "بِسْمِ اللَّהִ الرَّحْمَٰנِ الرَّחِיمِ",
    versesData: [],
    versesFile: "qadr",
  },
  {
    number: 98,
    name: "Al-Bayyinah",
    arabicName: "البينة",
    englishName: "The Clear Proof",
    verses: 8,
    juz: 30,
    type: "Medinan",
    revelationOrder: 100,
    description: "The clear evidence.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيমِ",
    versesData: [],
    versesFile: "bayyinah",
  },
  {
    number: 99,
    name: "Az-Zalzalah",
    arabicName: "الزلزلة",
    englishName: "The Earthquake",
    verses: 8,
    juz: 30,
    type: "Medinan",
    revelationOrder: 93,
    description: "The earthquake of the last hour.",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰנِ الرَّחִيمِ",
    versesData: [],
    versesFile: "zilzal",
  },
  {
    number: 100,
    name: "Al-Adiyat",
    arabicName: "العاديات",
    englishName: "The Courser",
    verses: 11,
    juz: 30,
    type: "Meccan",
    revelationOrder: 14,
    description: "The charging horses.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "adiyat",
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    arabicName: "القارعة",
    englishName: "The Calamity",
    verses: 11,
    juz: 30,
    type: "Meccan",
    revelationOrder: 30,
    description: "The striking calamity.",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰنِ الرَّحِيمِ",
    versesData: [],
    versesFile: "qariah",
  },
  {
    number: 102,
    name: "At-Takathur",
    arabicName: "التكاثر",
    englishName: "The Rivalry In World Increase",
    verses: 8,
    juz: 30,
    type: "Meccan",
    revelationOrder: 16,
    description: "The rivalry in accumulating wealth.",
    bismillah: "بِسْمִ اللَّهِ الرَّحْמَٰنِ الرَّחִيمِ",
    versesData: [],
    versesFile: "takathur",
  },
  {
    number: 103,
    name: "Al-Asr",
    arabicName: "العصر",
    englishName: "The Declining Day",
    verses: 3,
    juz: 30,
    type: "Meccan",
    revelationOrder: 13,
    description: "The afternoon or the declining day.",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰنִ الرَّحِيمِ",
    versesData: [],
    versesFile: "asr",
  },
  {
    number: 104,
    name: "Al-Humazah",
    arabicName: "الهمزة",
    englishName: "The Traducer",
    verses: 9,
    juz: 30,
    type: "Meccan",
    revelationOrder: 32,
    description: "The slanderer and backbiter.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّחِيمِ",
    versesData: [],
    versesFile: "humazah",
  },
  {
    number: 105,
    name: "Al-Fil",
    arabicName: "الفيل",
    englishName: "The Elephant",
    verses: 5,
    juz: 30,
    type: "Meccan",
    revelationOrder: 19,
    description: "The companions of the elephant.",
    bismillah: "بِسْمِ اللَّهِ الרَّحْمَٰنِ الرּَחِيمِ",
    versesData: [],
    versesFile: "fil",
  },
  {
    number: 106,
    name: "Quraish",
    arabicName: "قريش",
    englishName: "Quraish",
    verses: 4,
    juz: 30,
    type: "Meccan",
    revelationOrder: 29,
    description: "The tribe of Quraish.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْמَٰنِ الرَّحِיمِ",
    versesData: [],
    versesFile: "quraish",
  },
  {
    number: 107,
    name: "Al-Ma'un",
    arabicName: "الماعون",
    englishName: "The Small Kindnesses",
    verses: 7,
    juz: 30,
    type: "Meccan",
    revelationOrder: 17,
    description: "Small acts of kindness.",
    bismillah: "بِسْمِ اللَّהِ الرَّחْمَٰنِ الرَّحِימِ",
    versesData: [],
    versesFile: "maun",
  },
  {
    number: 108,
    name: "Al-Kawthar",
    arabicName: "الكوثر",
    englishName: "The Abundance",
    verses: 3,
    juz: 30,
    type: "Meccan",
    revelationOrder: 15,
    description: "The river of abundance in Paradise.",
    bismillah: "بِسْمِ اللَّהِ الرَّحْمَٰנִ الרَّחِיمِ",
    versesData: [],
    versesFile: "kawthar",
  },
  {
    number: 109,
    name: "Al-Kafirun",
    arabicName: "الكافرون",
    englishName: "The Disbelievers",
    verses: 6,
    juz: 30,
    type: "Meccan",
    revelationOrder: 18,
    description: "Those who reject faith.",
    bismillah: "بِسْمِ اللَّهِ الרَّحْمَٰنِ الרَّחִיمِ",
    versesData: [],
    versesFile: "kafirun",
  },
  {
    number: 110,
    name: "An-Nasr",
    arabicName: "النصر",
    englishName: "The Divine Support",
    verses: 3,
    juz: 30,
    type: "Medinan",
    revelationOrder: 114,
    description: "Divine help and victory.",
    bismillah: "بِسْמِ اللَّהִ الرَّحْمَٰנִ الרּَחִיمِ",
    versesData: [],
    versesFile: "nasr",
  },
  {
    number: 111,
    name: "Al-Masad",
    arabicName: "المسد",
    englishName: "The Palm Fibre",
    verses: 5,
    juz: 30,
    type: "Meccan",
    revelationOrder: 6,
    description: "The twisted rope of palm fiber.",
    bismillah: "بِسْمِ اللَّهِ الرَّחْمَٰنِ الרَّחִיمِ",
    versesData: [],
    versesFile: "masad",
  },
  {
    number: 112,
    name: "Al-Ikhlas",
    arabicName: "الإخلاص",
    englishName: "The Sincerity",
    verses: 4,
    juz: 30,
    type: "Meccan",
    revelationOrder: 22,
    description: "The purity of faith.",
    bismillah: "بِسْمِ اللَّهِ الרَّحْמَٰنِ الرَّחִيمִ",
    versesData: [],
    versesFile: "ikhlas",
  },
  {
    number: 113,
    name: "Al-Falaq",
    arabicName: "الفلق",
    englishName: "The Daybreak",
    verses: 5,
    juz: 30,
    type: "Meccan",
    revelationOrder: 20,
    description: "The dawn.",
    bismillah: "بِسْمِ اللَّهِ الرَّحْמَٰנִ الрَّحِיمِ",
    versesData: [],
    versesFile: "falaq",
  },
  {
    number: 114,
    name: "An-Nas",
    arabicName: "الناس",
    englishName: "Mankind",
    verses: 6,
    juz: 30,
    type: "Meccan",
    revelationOrder: 21,
    description: "Mankind.",
    bismillah: "بِسْمِ اللَّهِ الรَّحْمَٰنِ الรَّحِיমِ",
    versesData: [],
    versesFile: "nas",
  }
]

// Utility functions
export const getSurahByNumber = (number: number): Surah | undefined => {
  return QURAN_SURAHS.find((surah) => surah.number === number);
};

export const getSurahProgress = (
  surahNumber: number,
  lastVerseRead: number
): number => {
  const surah = getSurahByNumber(surahNumber);
  if (!surah) return 0;
  return Math.round((lastVerseRead / surah.verses) * 100);
};

// Enhanced utility functions for loading verses
export const loadSurahWithVerses = async (surahNumber: number): Promise<Surah | null> => {
  const surah = getSurahByNumber(surahNumber);
  if (!surah) return null;
  
  try {
    const verses = await loadSurahVersesByNumber(surahNumber);
    return {
      ...surah,
      versesData: verses
    };
  } catch (error) {
    console.error(`Error loading verses for surah ${surahNumber}:`, error);
    return surah;
  }
};

export const loadSurahByKey = async (surahKey: string): Promise<Surah | null> => {
  const surah = QURAN_SURAHS.find(s => s.versesFile === surahKey);
  if (!surah) return null;
  
  try {
    const verses = await loadSurahVerses(surahKey);
    return {
      ...surah,
      versesData: verses
    };
  } catch (error) {
    console.error(`Error loading verses for surah key ${surahKey}:`, error);
    return surah;
  }
};

export const getAvailableSurahs = (): Surah[] => {
  return QURAN_SURAHS.filter(surah => surah.versesFile);
};

// Re-export loading functions for convenience
export { getSurahKey, loadSurahVerses, loadSurahVersesByNumber } from './quran-data/loadSurahVerses';

// Example usage in a component:
/*
import { loadSurahVersesByNumber } from './quran-data/loadSurahVerses';

const [verses, setVerses] = useState<Verse[]>([]);

useEffect(() => {
  loadSurahVersesByNumber(1).then(setVerses);
}, []);
*/ 